### ISSUE TITLE
Native messaging application is outdated

### ISSUE THREAD

**Issue by billbrod** [Frewacom/pywalfox#54] opened 2020-12-09 21:56 UTC
I just installed `pywalfox` on a clean install of Firefox and whenever I start up firefox, I get the following error screen:

![Screenshot from 2020-12-09 16-54-28](https://user-images.githubusercontent.com/6338509/101693173-3f0b7c00-3a3f-11eb-96d7-9b61f4c4351b.png)

However, `pywalfox --version` on the command line (which I think is the native messaging application, right?) gives `v2.7.1`, the newest version. Do you know what's going on? This on Ubuntu 18.04, Firefox 83.0

And opening up Pywalfox settings, it is unable to fetch the theme colors (though it can switch between light and dark mode).

**Comment by Frewacom** [comment] 2020-12-09 22:07
Did you run `pywalfox install`? If you did, the Browser console (Tools > Web developer > Browser console) should hopefully show why it is not working as expected. The [Troubleshooting guide](https://github.com/Frewacom/pywalfox#troubleshooting) has some other things you may try if you haven't already.

**Comment by billbrod** [comment] 2020-12-09 22:14
I did. Here's a screenshot of the Browser console:

![Screenshot from 2020-12-09 17-11-24](https://user-images.githubusercontent.com/6338509/101694878-c22dd180-3a41-11eb-98bd-42169a7f51f5.png)

It's not obvious to me from the console what's going on. I tried following the steps in the Troubleshooting guide and none of them helped. 

Running various `pywalfox` commands from the command line don't output anything (even with `--verbose -p` flags) and don't seem to change anything in the browser.

**Comment by Frewacom** [comment] 2020-12-09 22:39
Are there any other messages/errors in the Browser console? 

> Running various pywalfox commands from the command line don't output anything (even with --verbose -p flags) and don't seem to change anything in the browser.

This is expected since Firefox must start it by itself for the communication to work.

Does `pywalfox start --verbose -p` not print anything either?

What does the Debugging section of the Pywalfox settings page say for you? 
If everything is setup correctly it should look something like this:
![image](https://user-images.githubusercontent.com/7253137/101696964-3df64100-3a77-11eb-9f70-4f975f74c716.png)

**Comment by billbrod** [comment] 2020-12-09 22:55
`pywalfox start --verbose -p` prints out the following (all of this gets printed when I run that, and then doesn't change, even when swapping between dark and light theme):

![Screenshot from 2020-12-09 17-48-51](https://user-images.githubusercontent.com/6338509/101698022-d58f6b80-3a46-11eb-8ae7-67efe6a8b734.png)

> What does the Debugging section of the Pywalfox settings page say for you?
 
Mine looks like that except it says `version not set` instead of `version 2.7`

Here's a photo of the complete browser console as of right this moment (The stuff included before was shortly after starting Firefox, when the only thing that I had done was receive the tab telling my pywalfox wasn't working)

![Screenshot from 2020-12-09 17-51-07](https://user-images.githubusercontent.com/6338509/101698331-4afb3c00-3a47-11eb-8850-6c5437277edb.png)

I'm not sure if those errors are coming from pywalfox -- when I click on the dropdown arrow, it tells me it's coming from an extension, but just gives me an alphanumeric string to identify it.

**Comment by Frewacom** [comment] 2020-12-09 23:12
Weird. Everything seems fine as far as I can tell and none of the messages in the Browser console looks related to Pywalfox. I’ll look into it tomorrow, but for now I am off to bed.

**Comment by billbrod** [comment] 2020-12-09 23:13
Alright, thanks!

**Comment by Frewacom** [comment] 2020-12-13 15:21
Sorry for the late reply. I'm still not quite sure why it is not working for you. If the native application fails to start or crashes during runtime the cause should be displayed in the Browser console. I suppose you could take a look at the debugging console for Pywalfox by navigating to `about:debugging` and then clicking on `Inspect`. You can then reload the addon via the console by typing `browser.runtime.reload()` and get a completely fresh log. 

If no errors or suspicious messages appear even after reloading, try fetching the colors from the Pywalfox settings page and check the console again.

**Comment by billbrod** [comment] 2020-12-15 02:43
Alright, now we've got some error messages!

![Screenshot from 2020-12-14 21-39-59](https://user-images.githubusercontent.com/6338509/102161369-36f37800-3e55-11eb-8c70-7f425b1bc5e4.png)

The "Could not establish connection" message repeats over and over. 

Does this help narrow it down?

**Comment by Frewacom** [comment] 2020-12-15 07:45
Sadly, it seems like the errors are from some other extension.

**Comment by billbrod** [comment] 2020-12-15 16:25
Ah. Well, thanks for your help. If I figure it out, I'll come back and update this, but otherwise, I think we can close the issue?

**Comment by Frewacom** [comment] 2020-12-15 20:44
I suppose we can close it for now. Sorry for not being of more help. I have tried to reproduce the issue on my computer but to no avail, nor do I see anything in the code that would cause this. Most likely it is something with your setup, but the lack of errors makes it really hard to debug. Native messaging has always been a bit tricky to setup because of all the different factors that affect it. 

The [Mozilla docs](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Native_messaging) are pretty decent and I would suggest to follow the guide there and try to set it up manually.

I hope you can get it resolved!

**Closed by Frewacom** 2020-12-15 20:44 UTC
